export const wedding_photobookImages = [
    {url: require("./1_main_wedding_photobook.jpg")},
    {url: require("./img13-1.jpg")},
    {url: require("./img13-2.jpg")},
    {url: require("./img13-3.jpg")},
    {url: require("./img13-4.jpg")},
    {url: require("./img13-5.jpg")},
    {url: require("./img13-6.jpg")},
    {url: require("./img13-7.jpg")},
    {url: require("./img13-8.jpg")},
    {url: require("./img13-9.jpg")},
    {url: require("./img13-10.jpg")},
    {url: require("./img13-11.jpg")},
    {url: require("./img13-12.jpg")},
    {url: require("./img13-13.jpg")},
    {url: require("./img13-14.jpg")},
    {url: require("./img13-15.jpg")},
    {url: require("./img13-16.jpg")},
    {url: require("./img13-17.jpg")},
    {url: require("./img13-18.jpg")},
    {url: require("./img13-19.jpg")},
    {url: require("./img13-20.jpg")},
    {url: require("./img13-21.jpg")},
    {url: require("./img13-22.jpg")},
    {url: require("./img13-23.jpg")},
    {url: require("./img13-24.jpg")},
]