export const graduate_bookImages = [
    {url: require("./img9-1.jpg")},
    {url: require("./img9-2.jpg")},
    {url: require("./img9-3.jpg")},
    {url: require("./img9-4.jpg")},
    {url: require("./1_main_graduate_book.jpg")},
    {url: require("./img9-6.jpg")},
    {url: require("./img9-7.jpg")},
    {url: require("./img9-8.jpg")},
    {url: require("./img9-9.jpg")},
    {url: require("./img9-10.jpg")},
    {url: require("./img9-11.jpg")},
    {url: require("./img9-12.jpg")},
    {url: require("./img9-13.jpg")},
    {url: require("./img9-14.jpg")},
    {url: require("./img9-15.jpg")},
    {url: require("./img9-16.jpg")},
    {url: require("./img9-17.jpg")},
    {url: require("./img9-18.jpg")},
    {url: require("./img9-19.jpg")},
    {url: require("./img9-20.jpg")},
    {url: require("./img9-21.jpg")},
    {url: require("./img9-22.jpg")},
    {url: require("./img9-23.jpg")},
    {url: require("./img9-24.jpg")},
    {url: require("./img9-25.jpg")},
    {url: require("./img9-26.jpg")},
]