export const portraitImages = [
    {url: require("./1_main_portrait.jpg")},
    {url: require("./img4-1.jpg")},
    {url: require("./img4-2.jpg")},
    {url: require("./img4-3.jpg")},
    {url: require("./img4-4.jpg")},
    {url: require("./img4-5.jpg")},
    {url: require("./img4-6.jpg")},
    {url: require("./img4-7.jpg")},
    {url: require("./img4-8.jpg")},
    {url: require("./img4-9.jpg")},
    {url: require("./img4-10.jpg")},
    {url: require("./img4-11.jpg")},
    {url: require("./img4-12.jpg")},
    {url: require("./img4-13.jpg")},
    {url: require("./img4-14.jpg")},
    {url: require("./img4-15.jpg")},
    {url: require("./img4-16.jpg")},
    {url: require("./img4-7.jpg")},
    {url: require("./img4-18.jpg")},
    {url: require("./img4-19.jpg")},
    {url: require("./img4-20.jpg")},
    {url: require("./img4-21.jpg")},

]