export const genreImages = [
    {url: require("./1_main_genre.jpg")},
    {url: require("./img5-1.jpg")},
    {url: require("./img5-2.jpg")},
    {url: require("./img5-3.jpg")},
    {url: require("./img5-4.jpg")},
    {url: require("./img5-5.jpg")},
    {url: require("./img5-6.jpg")},
    {url: require("./img5-7.jpg")},
    {url: require("./img5-8.jpg")},
    {url: require("./img5-9.jpg")},
    {url: require("./img5-10.jpg")},
    {url: require("./img5-11.jpg")},
    {url: require("./img5-12.jpg")},
    {url: require("./img5-13.jpg")},
    {url: require("./img5-14.jpg")},
    {url: require("./img5-15.jpg")},
    {url: require("./img5-16.jpg")},
    {url: require("./img5-17.jpg")},
    {url: require("./img5-18.jpg")},
    {url: require("./img5-19.jpg")},
    {url: require("./img5-20.jpg")},
]