export const presentsImages = [
    {url: require("./1_main_presents.jpg")},
    {url: require("./img12-1.jpg")},
    {url: require("./img12-2.jpg")},
    {url: require("./img12-3.jpg")},

    {url: require("./img12-7.jpg")},
    {url: require("./img12-8.jpg")},
    {url: require("./img12-9.jpg")},
    {url: require("./img12-10.jpg")},
    {url: require("./img12-11.jpg")},
    {url: require("./img12-12.jpg")},
    {url: require("./img12-13.jpg")},
    {url: require("./img12-14.jpg")},
    {url: require("./img12-15.jpg")},
    {url: require("./img12-16.jpg")},
    {url: require("./img12-17.jpg")},
    {url: require("./img12-18.jpg")},
    {url: require("./img12-19.jpg")},
    {url: require("./img12-20.jpg")},
    {url: require("./img12-21.jpg")},
    {url: require("./img12-22.jpg")},
    {url: require("./img12-23.jpg")},
    {url: require("./img12-24.jpg")},
    {url: require("./img12-25.jpg")},
    {url: require("./img12-26.jpg")},
    {url: require("./img12-27.jpg")},
    {url: require("./img12-28.jpg")},
]